
[project]
name = "storage"
requires-python = ">= 3.11"
dynamic = ["version"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = ["**/*.py"]
exclude = ["**/__pycache__", ".venv"]
ignore = []

typeCheckingMode = "strict"
reportUnknownParameterType = true
reportMissingParameterType = true
reportUnknownMemberType = false
